server:
  port: 0 # Server information for embedded jetty
#  url: http://16.16.16.16:8080 #the master base url used by the client to upload uber jar and data feed files

client:
  port: 0 # Port number for the actor system that host the worker actors
  role: "client" # The name of the role each actor uses (role1,role2...role5 etc)

client.accessKey: optional #optional access key for the partition
client.partitionName: public
client.dataFeedPath: "" # path to the data feed file
client.quiet: false
client.parallelism: 1
client.remoteArtifact: false


application.title: distGatling

logging.level.root: ERROR
logging.level.com.walmart.gatling: INFO
logging.level.com.walmart.gatling.Client: ERROR
